/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ralphmcdougallgrade10pat;

import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author Ralph McDougall 4/11/2016
 */
public class GUIFeedback extends javax.swing.JFrame {

    /**
     * This gives the user feedback by showing them their time, their medal
     * and letting them know what time to aim for for the next medal.
     */
    
    private int NUM_QUESTIONS = 0;
    private int NUM_MILLISECONDS = 0;
    
    private GUIQuestion parentGUI = null;
    
    private final int BIG_NUM = 1000000000; // It should take at least a year to reach this score
    
    // Array of the maximum time required to achieve a goal
    // {WR, G, S, B, None}
    private int[] GOAL_SPLITS = {0, 5000, 20000, 30000, 40000, BIG_NUM}; // Still to be scaled
    
    private String GOAL = "";
    private String[] GOALS = {"World Record", "World Record", "Gold Medal", "Silver Medal", "Bronze Medal", "No Medal"};
    
    private String NEXT_GOAL = "";
    private int NEXT_TIME = 0;
    
    private int MEDAL_NUM = 0;
    
    // {G, S, B, N}
    private String[] MEDAL_IMG_PATHS = {"../resources/GoldMedal.png", "../resources/SilverMedal.png", "../resources/BronzeMedal.png", "../resources/NoMedal.png"};
    
    private int TARGET = 0;
    private int DIFFICULTY = 0;
    private int OPERATOR = 0;
    
    private String NAME = "";
    
    public GUIFeedback(GUIQuestion _parentGUI, int target, int difficulty, int operator, int millis, String name) throws IOException {
        initComponents();
        
        this.parentGUI = _parentGUI;
        
        this.NUM_QUESTIONS = target;
        this.NUM_MILLISECONDS = millis;
        
        this.TARGET = target;
        this.DIFFICULTY = difficulty;
        this.OPERATOR = operator;
        this.NAME = name;
        
        this.setLocationRelativeTo(this.parentGUI);
        
        this.updateRecord(); // Get the record
        this.getGoal(); // Get the next goal

        this.setMessageLabel(); // Set the label of the message that is displayed
        this.setGoalLabels(); // Set the label of the goals to achieve
        
        this.setMedal(); // Set the image of the medal
        
        this.recordTime(); // Try to add the user's time to the top 8 times
    }
    
    private void updateRecord() throws IOException
    {
        // Get the record for the DIFFICULTY, OPERATOR and TARGET
        RecordsFileHandler rfh = new RecordsFileHandler(this.DIFFICULTY, this.OPERATOR, this.TARGET);
        this.GOAL_SPLITS[1] = rfh.getTime(0);
    }
    
    private void setMessageLabel()
    {
        // Set the label that shoes the message
        
        // Construct the message
        String mess = "You completed " + NUM_QUESTIONS + " ";
        mess += "questions in " + ( (double) (NUM_MILLISECONDS / 1000.0) ) + " seconds!";
        lblMessage.setText(mess); // Set the label
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlMessage = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        pnlMedal = new javax.swing.JPanel();
        pnlMedalTitle = new javax.swing.JLabel();
        lblMedalImg = new javax.swing.JLabel();
        pnlGoal = new javax.swing.JPanel();
        lblNextGoalName = new javax.swing.JLabel();
        lblNextGoalTime = new javax.swing.JLabel();
        lblCurrGoalName = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(255, 255, 51));

        pnlMessage.setBackground(new java.awt.Color(153, 255, 153));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        lblTitle.setText("Congratulations!");

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblMessage.setText("You completed 10 questions in 72 seconds!");
        lblMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlMessageLayout = new javax.swing.GroupLayout(pnlMessage);
        pnlMessage.setLayout(pnlMessageLayout);
        pnlMessageLayout.setHorizontalGroup(
            pnlMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMessageLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMessageLayout.createSequentialGroup()
                        .addComponent(lblMessage)
                        .addGap(135, 135, 135))))
        );
        pnlMessageLayout.setVerticalGroup(
            pnlMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblMessage)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pnlMedal.setBackground(new java.awt.Color(255, 255, 255));

        pnlMedalTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pnlMedalTitle.setText("Medal:");

        lblMedalImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/GoldMedal.png"))); // NOI18N

        javax.swing.GroupLayout pnlMedalLayout = new javax.swing.GroupLayout(pnlMedal);
        pnlMedal.setLayout(pnlMedalLayout);
        pnlMedalLayout.setHorizontalGroup(
            pnlMedalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMedalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMedalTitle)
                .addGap(134, 134, 134))
            .addGroup(pnlMedalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedalImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMedalLayout.setVerticalGroup(
            pnlMedalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMedalTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMedalImg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlGoal.setBackground(new java.awt.Color(255, 255, 255));

        lblNextGoalName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNextGoalName.setText("Your next goal is: World Record!");

        lblNextGoalTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNextGoalTime.setText("Next goal target time: 60 seconds!");

        lblCurrGoalName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCurrGoalName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrGoalName.setText("You achieved: Gold Medal");

        javax.swing.GroupLayout pnlGoalLayout = new javax.swing.GroupLayout(pnlGoal);
        pnlGoal.setLayout(pnlGoalLayout);
        pnlGoalLayout.setHorizontalGroup(
            pnlGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGoalLayout.createSequentialGroup()
                .addGroup(pnlGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGoalLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblNextGoalTime))
                    .addGroup(pnlGoalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurrGoalName)
                            .addComponent(lblNextGoalName))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlGoalLayout.setVerticalGroup(
            pnlGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGoalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrGoalName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNextGoalName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNextGoalTime)
                .addGap(100, 100, 100))
        );

        btnContinue.setBackground(new java.awt.Color(51, 255, 51));
        btnContinue.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlGoal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(pnlMedal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(pnlGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(171, 171, 171))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(pnlMedal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // "Continue" button pressed
        close();
    }//GEN-LAST:event_btnContinueActionPerformed

    private void close()
    {
        this.parentGUI.stop(); // Stop the GUIQuestion that is the parent of this
        this.dispose(); // Close this screen
    }
    
    private void getGoal()
    {
        // This method gets the goal that the user can aim for
        
        for (int i = 0; i < 6; ++i)
        {
            // Scale the times up according to the number of questions answered
            int scaleFactor = this.NUM_QUESTIONS / 10;
            int nextScaleFactor = this.NUM_QUESTIONS / 10; // Scale the next goal
            
            if (i == 0) // The record must not be scaled
            {
                scaleFactor = 1;
            }
            if (i == 1) // The next goal is the record
            {
                nextScaleFactor = 1;
            }
            
            // Check which time the user has beaten
            if (this.NUM_MILLISECONDS <= this.GOAL_SPLITS[i + 1] * scaleFactor)
            {
                this.GOAL = GOALS[i + 1]; // Get the goal name
                this.NEXT_GOAL = GOALS[i]; // Get the next goal
                this.NEXT_TIME = this.GOAL_SPLITS[i] * nextScaleFactor; // Next goal time
                this.MEDAL_NUM = i; // The index of the appropriate medal
                break;
            }
        }
    }
    
    private void setGoalLabels()
    {
        // Set the text of the labels showing the goals to achieve as well as current goal
        lblCurrGoalName.setText("You achieved: " + this.GOAL);
        lblNextGoalName.setText("Your next goal: " + this.NEXT_GOAL + "!");
        lblNextGoalTime.setText("Next goal target time " + (this.NEXT_TIME / 1000.0) + " seconds!");
    }
    
    private void setMedal()
    {
        // Set the image of the medal
        
        switch(this.MEDAL_NUM)
        {
            case 0:
            case 1:
                // Gold
                { // "icon" scope hack
                ImageIcon icon = new ImageIcon(getClass().getResource(MEDAL_IMG_PATHS[0]));
                this.lblMedalImg.setIcon(icon);
                }
                break;
            case 2:
                // Silver
                {
                // Code "borrowed" from StackExchange
                ImageIcon icon = new ImageIcon(getClass().getResource(MEDAL_IMG_PATHS[1]));
                this.lblMedalImg.setIcon(icon);
                }
                break;
            case 3:
                // Bronze
                {
                ImageIcon icon = new ImageIcon(getClass().getResource(MEDAL_IMG_PATHS[2]));
                this.lblMedalImg.setIcon(icon);
                }
                break;
            default:
                // None
                {
                ImageIcon icon = new ImageIcon(getClass().getResource(MEDAL_IMG_PATHS[3]));
                this.lblMedalImg.setIcon(icon);
                }
                break;
        }
    }
    
    private void recordTime() throws IOException
    {
        // Try to add the user's time to the top 8 times
        
        RecordsFileHandler rfh = new RecordsFileHandler(this.DIFFICULTY, this.OPERATOR, this.TARGET);
        rfh.insert(this.NUM_MILLISECONDS, this.NAME); // Insert the time and name
        rfh.writeData();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel lblCurrGoalName;
    private javax.swing.JLabel lblMedalImg;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNextGoalName;
    private javax.swing.JLabel lblNextGoalTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlGoal;
    private javax.swing.JPanel pnlMedal;
    private javax.swing.JLabel pnlMedalTitle;
    private javax.swing.JPanel pnlMessage;
    // End of variables declaration//GEN-END:variables
}
