/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ralphmcdougallgrade10pat;

/**
 *
 * @author Ralph McDougall 4/11/2016
 */
public class GUIOptions extends javax.swing.JFrame {
    /**
     * This GUI displays all of the options that the user may pick
     * and allows the user to choose their preferences.
     */
    
    GUIStart parentGUI; // The GUI that opened this screen
    
    private int SELECTED_OPERATION = 0; // The "index" of the selected operation
    private int SELECTED_DIFFICULTY = 1; // The "index" of the selected difficulty
    private int SELECTED_TARGET = 10; // The selected target score
    
    
    public GUIOptions(GUIStart _parentGUI, int op, int diff, int target) {
        initComponents();
        
        this.parentGUI = _parentGUI;
        
        // Set the selected options to be the same options that are selected in the main screen
        this.SELECTED_OPERATION = op;
        this.SELECTED_DIFFICULTY = diff;
        this.SELECTED_TARGET = target;
        
        this.setLocationRelativeTo(this.parentGUI);
        
        // Select the appropriate buttons
        this.selectOperationButton();
        this.selectDifficultyButton();
        this.selectTargetButton();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpTarget = new javax.swing.ButtonGroup();
        btngrpDifficulty = new javax.swing.ButtonGroup();
        btngrpOperation = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        pnlOptions = new javax.swing.JPanel();
        pnlOperations = new javax.swing.JPanel();
        radbtnDivide = new javax.swing.JRadioButton();
        radbtnMultiply = new javax.swing.JRadioButton();
        radbtnSubtract = new javax.swing.JRadioButton();
        radbtnAdd = new javax.swing.JRadioButton();
        lblOperations = new javax.swing.JLabel();
        pnlDifficulty = new javax.swing.JPanel();
        radbtnLev4 = new javax.swing.JRadioButton();
        radbtnLev3 = new javax.swing.JRadioButton();
        radbtnLev1 = new javax.swing.JRadioButton();
        radbtnLev2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        pnlTargetScore = new javax.swing.JPanel();
        radbtnOption40 = new javax.swing.JRadioButton();
        radbtnOption30 = new javax.swing.JRadioButton();
        radbtnOption20 = new javax.swing.JRadioButton();
        radbtnOption10 = new javax.swing.JRadioButton();
        lblOperations1 = new javax.swing.JLabel();
        radbtnOption50 = new javax.swing.JRadioButton();
        radbtnOption100 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 675));
        setMinimumSize(new java.awt.Dimension(900, 675));
        setPreferredSize(new java.awt.Dimension(900, 675));

        pnlBackground.setBackground(new java.awt.Color(255, 255, 0));
        pnlBackground.setMaximumSize(new java.awt.Dimension(900, 675));
        pnlBackground.setMinimumSize(new java.awt.Dimension(900, 675));
        pnlBackground.setPreferredSize(new java.awt.Dimension(900, 675));

        pnlTitle.setBackground(new java.awt.Color(51, 255, 51));

        lblTitle.setBackground(new java.awt.Color(0, 255, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("OPTIONS");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBack.setBackground(new java.awt.Color(0, 255, 0));
        btnBack.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        pnlOptions.setBackground(new java.awt.Color(0, 255, 0));

        pnlOperations.setBackground(new java.awt.Color(255, 255, 255));

        radbtnDivide.setBackground(new java.awt.Color(255, 255, 255));
        btngrpOperation.add(radbtnDivide);
        radbtnDivide.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnDivide.setText("Division");

        radbtnMultiply.setBackground(new java.awt.Color(255, 255, 255));
        btngrpOperation.add(radbtnMultiply);
        radbtnMultiply.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnMultiply.setText("Multiplication");

        radbtnSubtract.setBackground(new java.awt.Color(255, 255, 255));
        btngrpOperation.add(radbtnSubtract);
        radbtnSubtract.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnSubtract.setText("Subtraction");

        radbtnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btngrpOperation.add(radbtnAdd);
        radbtnAdd.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnAdd.setText("Addition");

        lblOperations.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblOperations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOperations.setText("OPERATION");

        javax.swing.GroupLayout pnlOperationsLayout = new javax.swing.GroupLayout(pnlOperations);
        pnlOperations.setLayout(pnlOperationsLayout);
        pnlOperationsLayout.setHorizontalGroup(
            pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlOperationsLayout.createSequentialGroup()
                        .addGroup(pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radbtnAdd)
                            .addComponent(radbtnSubtract)
                            .addComponent(radbtnMultiply)
                            .addComponent(radbtnDivide))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlOperationsLayout.setVerticalGroup(
            pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOperations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radbtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnSubtract)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnMultiply)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnDivide)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDifficulty.setBackground(new java.awt.Color(255, 255, 255));

        radbtnLev4.setBackground(new java.awt.Color(255, 255, 255));
        btngrpDifficulty.add(radbtnLev4);
        radbtnLev4.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnLev4.setText("Insane");

        radbtnLev3.setBackground(new java.awt.Color(255, 255, 255));
        btngrpDifficulty.add(radbtnLev3);
        radbtnLev3.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnLev3.setText("Difficult");

        radbtnLev1.setBackground(new java.awt.Color(255, 255, 255));
        btngrpDifficulty.add(radbtnLev1);
        radbtnLev1.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnLev1.setText("Easy");

        radbtnLev2.setBackground(new java.awt.Color(255, 255, 255));
        btngrpDifficulty.add(radbtnLev2);
        radbtnLev2.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnLev2.setText("Moderate");
        radbtnLev2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnLev2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DIFFICULTY");

        javax.swing.GroupLayout pnlDifficultyLayout = new javax.swing.GroupLayout(pnlDifficulty);
        pnlDifficulty.setLayout(pnlDifficultyLayout);
        pnlDifficultyLayout.setHorizontalGroup(
            pnlDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDifficultyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(pnlDifficultyLayout.createSequentialGroup()
                        .addGroup(pnlDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radbtnLev1)
                            .addComponent(radbtnLev2)
                            .addComponent(radbtnLev3)
                            .addComponent(radbtnLev4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDifficultyLayout.setVerticalGroup(
            pnlDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDifficultyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radbtnLev1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnLev2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnLev3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnLev4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTargetScore.setBackground(new java.awt.Color(255, 255, 255));

        radbtnOption40.setBackground(new java.awt.Color(255, 255, 255));
        btngrpTarget.add(radbtnOption40);
        radbtnOption40.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnOption40.setText("40");

        radbtnOption30.setBackground(new java.awt.Color(255, 255, 255));
        btngrpTarget.add(radbtnOption30);
        radbtnOption30.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnOption30.setText("30");

        radbtnOption20.setBackground(new java.awt.Color(255, 255, 255));
        btngrpTarget.add(radbtnOption20);
        radbtnOption20.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnOption20.setText("20");

        radbtnOption10.setBackground(new java.awt.Color(255, 255, 255));
        btngrpTarget.add(radbtnOption10);
        radbtnOption10.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnOption10.setText("10");

        lblOperations1.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        lblOperations1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOperations1.setText("TARGET SCORE");

        radbtnOption50.setBackground(new java.awt.Color(255, 255, 255));
        btngrpTarget.add(radbtnOption50);
        radbtnOption50.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnOption50.setText("50");

        radbtnOption100.setBackground(new java.awt.Color(255, 255, 255));
        btngrpTarget.add(radbtnOption100);
        radbtnOption100.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        radbtnOption100.setText("100");

        javax.swing.GroupLayout pnlTargetScoreLayout = new javax.swing.GroupLayout(pnlTargetScore);
        pnlTargetScore.setLayout(pnlTargetScoreLayout);
        pnlTargetScoreLayout.setHorizontalGroup(
            pnlTargetScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTargetScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTargetScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOperations1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTargetScoreLayout.createSequentialGroup()
                        .addGroup(pnlTargetScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radbtnOption10)
                            .addComponent(radbtnOption20)
                            .addComponent(radbtnOption30)
                            .addComponent(radbtnOption40)
                            .addComponent(radbtnOption50)
                            .addComponent(radbtnOption100))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTargetScoreLayout.setVerticalGroup(
            pnlTargetScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTargetScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOperations1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radbtnOption10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnOption20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnOption30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnOption40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnOption50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnOption100)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions);
        pnlOptions.setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTargetScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOptionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTargetScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDifficulty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // "Back" button pressed
        close();
    }//GEN-LAST:event_btnBackActionPerformed

    private void radbtnLev2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnLev2ActionPerformed
        
    }//GEN-LAST:event_radbtnLev2ActionPerformed

    private void close()
    {
        // Close the screen
        
        // Get the buttons that have been selected
        getOperationButton();
        getDifficultyButton();
        getTargetButton();
        
        // Update the options in the main screen
        setParentGUIOptions();
        
        // Set the main screen to be visible again
        parentGUI.setVisible(true);
        // Get rid of this screen
        this.dispose();
    }
    
    private void selectOperationButton()
    {
        // Select the chosen OPERATION button
        
        switch (this.SELECTED_OPERATION)
        {
            case 0:
                radbtnAdd.setSelected(true);
                break;
            case 1:
                radbtnSubtract.setSelected(true);
                break;
            case 2:
                radbtnMultiply.setSelected(true);
                break;
            case 3:
                radbtnDivide.setSelected(true);
                break;
            default:
                break;
        }
    }
    
    private void selectDifficultyButton()
    {
        // Select the chosen DIFFICULTY button
        
        switch (this.SELECTED_DIFFICULTY)
        {
            case 1:
                radbtnLev1.setSelected(true);
                break;
            case 2:
                radbtnLev2.setSelected(true);
                break;
            case 3:
                radbtnLev3.setSelected(true);
                break;
            case 4:
                radbtnLev4.setSelected(true);
                break;
            default:
                break;
        }
    }
    
    private void selectTargetButton()
    {
        // Select the chosen TARGET button
        switch (this.SELECTED_TARGET)
        {
            case 10:
                radbtnOption10.setSelected(true);
                break;
            case 20:
                radbtnOption20.setSelected(true);
                break;
            case 30:
                radbtnOption30.setSelected(true);
                break;
            case 40:
                radbtnOption40.setSelected(true);
                break;
            case 50:
                radbtnOption50.setSelected(true);
                break;
            case 100:
                radbtnOption100.setSelected(true);
                break;
            default:
                break;
        }
    }
    
    
    private void getOperationButton()
    {
        // Get the OPERATION button that is selected
        
        if (radbtnAdd.isSelected())
        {
            this.SELECTED_OPERATION = 0;
        }
        else if (radbtnSubtract.isSelected())
        {
            this.SELECTED_OPERATION = 1;
        }
        else if (radbtnMultiply.isSelected())
        {
            this.SELECTED_OPERATION = 2;
        }
        else if (radbtnDivide.isSelected())
        {
            this.SELECTED_OPERATION = 3;
        }
    }
    
    private void getDifficultyButton()
    {
        // Get the DIFFICULTY button that is selected
        
        if (radbtnLev1.isSelected())
        {
            this.SELECTED_DIFFICULTY = 1;
        }
        else if (radbtnLev2.isSelected())
        {
            this.SELECTED_DIFFICULTY = 2;
        }
        else if (radbtnLev3.isSelected())
        {
            this.SELECTED_DIFFICULTY = 3;
        }
        else if (radbtnLev4.isSelected())
        {
            this.SELECTED_DIFFICULTY = 4;
        }
    }
    
    private void getTargetButton()
    {
        // Get the TARGET button that is selected
        
        if (radbtnOption10.isSelected())
        {
            this.SELECTED_TARGET = 10;
        }
        else if (radbtnOption20.isSelected())
        {
            this.SELECTED_TARGET = 20;
        }
        else if (radbtnOption30.isSelected())
        {
            this.SELECTED_TARGET = 30;
        }
        else if (radbtnOption40.isSelected())
        {
            this.SELECTED_TARGET = 40;
        }
        else if (radbtnOption50.isSelected())
        {
            this.SELECTED_TARGET = 50;
        }
        else if (radbtnOption100.isSelected())
        {
            this.SELECTED_TARGET = 100;
        }
    }
    
    private void setParentGUIOptions()
    {
        // Set the selected options in the main screen
        
        parentGUI.SELECTED_OPERATOR = this.SELECTED_OPERATION;
        parentGUI.SELECTED_DIFFICULTY = this.SELECTED_DIFFICULTY;
        parentGUI.SELECTED_TARGET = this.SELECTED_TARGET;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    javax.swing.ButtonGroup btngrpDifficulty;
    private javax.swing.ButtonGroup btngrpOperation;
    private javax.swing.ButtonGroup btngrpTarget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOperations;
    private javax.swing.JLabel lblOperations1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlDifficulty;
    private javax.swing.JPanel pnlOperations;
    private javax.swing.JPanel pnlOptions;
    private javax.swing.JPanel pnlTargetScore;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JRadioButton radbtnAdd;
    private javax.swing.JRadioButton radbtnDivide;
    private javax.swing.JRadioButton radbtnLev1;
    private javax.swing.JRadioButton radbtnLev2;
    private javax.swing.JRadioButton radbtnLev3;
    private javax.swing.JRadioButton radbtnLev4;
    private javax.swing.JRadioButton radbtnMultiply;
    private javax.swing.JRadioButton radbtnOption10;
    private javax.swing.JRadioButton radbtnOption100;
    private javax.swing.JRadioButton radbtnOption20;
    private javax.swing.JRadioButton radbtnOption30;
    private javax.swing.JRadioButton radbtnOption40;
    private javax.swing.JRadioButton radbtnOption50;
    private javax.swing.JRadioButton radbtnSubtract;
    // End of variables declaration//GEN-END:variables
}
