/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ralphmcdougallgrade10pat;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ralph McDougall 4/11/2016
 */

public class GUIRecords extends javax.swing.JFrame {
    /**
     * This screen shows the best times for each respective event.
     */
    
    int CHOSEN_OPERATION_INDEX = 0;
    int CHOSEN_TARGET_INDEX = 0;
    int CHOSEN_DIFFICULTY_INDEX = 0;
    
    int CHOSEN_OPERATION = 0;
    int CHOSEN_TARGET = 10;
    int CHOSEN_DIFFICULTY = 1;
    
    GUIStart parentGUI = null;
    
    
    public GUIRecords(GUIStart _parentGUI) {
        initComponents();
        this.parentGUI = _parentGUI;
        this.setLocationRelativeTo(this.parentGUI); // Center the screen
        this.updateRecords(); // Get the default selected records
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlSelection = new javax.swing.JPanel();
        pnlOperationSelect = new javax.swing.JPanel();
        lblOperation = new javax.swing.JLabel();
        cmbxOperation = new javax.swing.JComboBox<>();
        pnlOperationSelect1 = new javax.swing.JPanel();
        lblTarget = new javax.swing.JLabel();
        cmbxTarget = new javax.swing.JComboBox<>();
        pnlOperationSelect2 = new javax.swing.JPanel();
        lblDifficulty = new javax.swing.JLabel();
        cmbxDifficulty = new javax.swing.JComboBox<>();
        btnGetRecords = new javax.swing.JButton();
        pnlRecordDisplay = new javax.swing.JPanel();
        pnlPlace1 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        lblTime1 = new javax.swing.JLabel();
        lblPos1 = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblName10 = new javax.swing.JLabel();
        pnlPlace10 = new javax.swing.JPanel();
        lblName2 = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        lblPos2 = new javax.swing.JLabel();
        pnlPlace11 = new javax.swing.JPanel();
        lblName3 = new javax.swing.JLabel();
        lblTime3 = new javax.swing.JLabel();
        lblPos3 = new javax.swing.JLabel();
        pnlPlace12 = new javax.swing.JPanel();
        lblName4 = new javax.swing.JLabel();
        lblTime4 = new javax.swing.JLabel();
        lblPos4 = new javax.swing.JLabel();
        pnlPlace13 = new javax.swing.JPanel();
        lblName5 = new javax.swing.JLabel();
        lblTime5 = new javax.swing.JLabel();
        lblPos5 = new javax.swing.JLabel();
        pnlPlace14 = new javax.swing.JPanel();
        lblName6 = new javax.swing.JLabel();
        lblTime6 = new javax.swing.JLabel();
        lblPos6 = new javax.swing.JLabel();
        pnlPlace15 = new javax.swing.JPanel();
        lblName7 = new javax.swing.JLabel();
        lblTime7 = new javax.swing.JLabel();
        lblPos7 = new javax.swing.JLabel();
        pnlPlace16 = new javax.swing.JPanel();
        lblName8 = new javax.swing.JLabel();
        lblTime8 = new javax.swing.JLabel();
        lblPos8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 675));
        setMinimumSize(new java.awt.Dimension(900, 675));
        setName("frame"); // NOI18N
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(0, 255, 0));
        pnlBackground.setMaximumSize(new java.awt.Dimension(900, 675));
        pnlBackground.setMinimumSize(new java.awt.Dimension(900, 675));

        btnBack.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        pnlTitle.setBackground(new java.awt.Color(255, 255, 0));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Records");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSelection.setBackground(new java.awt.Color(255, 255, 255));

        pnlOperationSelect.setBackground(new java.awt.Color(255, 255, 0));

        lblOperation.setBackground(new java.awt.Color(255, 255, 51));
        lblOperation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblOperation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOperation.setText("Operation");

        cmbxOperation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Addition", "Subtraction", "Multiplication", "Division" }));
        cmbxOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxOperationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOperationSelectLayout = new javax.swing.GroupLayout(pnlOperationSelect);
        pnlOperationSelect.setLayout(pnlOperationSelectLayout);
        pnlOperationSelectLayout.setHorizontalGroup(
            pnlOperationSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbxOperation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOperationSelectLayout.setVerticalGroup(
            pnlOperationSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOperationSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOperationSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbxOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(lblOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlOperationSelect1.setBackground(new java.awt.Color(255, 255, 0));

        lblTarget.setBackground(new java.awt.Color(255, 255, 51));
        lblTarget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTarget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTarget.setText("Target");

        cmbxTarget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxTarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "100" }));
        cmbxTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTargetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOperationSelect1Layout = new javax.swing.GroupLayout(pnlOperationSelect1);
        pnlOperationSelect1.setLayout(pnlOperationSelect1Layout);
        pnlOperationSelect1Layout.setHorizontalGroup(
            pnlOperationSelect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationSelect1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbxTarget, 0, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOperationSelect1Layout.setVerticalGroup(
            pnlOperationSelect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOperationSelect1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOperationSelect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbxTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(lblTarget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlOperationSelect2.setBackground(new java.awt.Color(255, 255, 0));

        lblDifficulty.setBackground(new java.awt.Color(255, 255, 0));
        lblDifficulty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDifficulty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDifficulty.setText("Difficulty");

        cmbxDifficulty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Moderate", "Difficult", "Insane" }));
        cmbxDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxDifficultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOperationSelect2Layout = new javax.swing.GroupLayout(pnlOperationSelect2);
        pnlOperationSelect2.setLayout(pnlOperationSelect2Layout);
        pnlOperationSelect2Layout.setHorizontalGroup(
            pnlOperationSelect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationSelect2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbxDifficulty, 0, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOperationSelect2Layout.setVerticalGroup(
            pnlOperationSelect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOperationSelect2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOperationSelect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbxDifficulty, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(lblDifficulty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnGetRecords.setBackground(new java.awt.Color(255, 255, 0));
        btnGetRecords.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnGetRecords.setText("Get Records");
        btnGetRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSelectionLayout = new javax.swing.GroupLayout(pnlSelection);
        pnlSelection.setLayout(pnlSelectionLayout);
        pnlSelectionLayout.setHorizontalGroup(
            pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSelectionLayout.createSequentialGroup()
                        .addComponent(btnGetRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlOperationSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOperationSelect2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOperationSelect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSelectionLayout.setVerticalGroup(
            pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOperationSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlOperationSelect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlOperationSelect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGetRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlRecordDisplay.setBackground(new java.awt.Color(255, 255, 255));

        pnlPlace1.setBackground(new java.awt.Color(255, 255, 0));

        lblName1.setBackground(new java.awt.Color(255, 255, 255));
        lblName1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName1.setText("Ralph");

        lblTime1.setBackground(new java.awt.Color(255, 255, 255));
        lblTime1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime1.setText("5");

        lblPos1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPos1.setText("1");

        javax.swing.GroupLayout pnlPlace1Layout = new javax.swing.GroupLayout(pnlPlace1);
        pnlPlace1.setLayout(pnlPlace1Layout);
        pnlPlace1Layout.setHorizontalGroup(
            pnlPlace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPos1)
                .addGap(18, 18, 18)
                .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlace1Layout.setVerticalGroup(
            pnlPlace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPlace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPos1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHeader.setBackground(new java.awt.Color(255, 255, 0));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setText("Name");

        lblName10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName10.setText("Time (seconds)");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblName10)
                .addGap(49, 49, 49))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblName10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPlace10.setBackground(new java.awt.Color(255, 255, 0));

        lblName2.setBackground(new java.awt.Color(255, 255, 255));
        lblName2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName2.setText("Ralph");

        lblTime2.setBackground(new java.awt.Color(255, 255, 255));
        lblTime2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime2.setText("5");

        lblPos2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPos2.setText("2");

        javax.swing.GroupLayout pnlPlace10Layout = new javax.swing.GroupLayout(pnlPlace10);
        pnlPlace10.setLayout(pnlPlace10Layout);
        pnlPlace10Layout.setHorizontalGroup(
            pnlPlace10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPos2)
                .addGap(18, 18, 18)
                .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlace10Layout.setVerticalGroup(
            pnlPlace10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlace10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTime2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPlace10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPos2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPlace11.setBackground(new java.awt.Color(255, 255, 0));

        lblName3.setBackground(new java.awt.Color(255, 255, 255));
        lblName3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName3.setText("Ralph");

        lblTime3.setBackground(new java.awt.Color(255, 255, 255));
        lblTime3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTime3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime3.setText("5");

        lblPos3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPos3.setText("3");

        javax.swing.GroupLayout pnlPlace11Layout = new javax.swing.GroupLayout(pnlPlace11);
        pnlPlace11.setLayout(pnlPlace11Layout);
        pnlPlace11Layout.setHorizontalGroup(
            pnlPlace11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPos3)
                .addGap(18, 18, 18)
                .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlace11Layout.setVerticalGroup(
            pnlPlace11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlace11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTime3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPlace11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPos3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPlace12.setBackground(new java.awt.Color(255, 255, 0));

        lblName4.setBackground(new java.awt.Color(255, 255, 255));
        lblName4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName4.setText("Ralph");

        lblTime4.setBackground(new java.awt.Color(255, 255, 255));
        lblTime4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTime4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime4.setText("5");

        lblPos4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPos4.setText("4");

        javax.swing.GroupLayout pnlPlace12Layout = new javax.swing.GroupLayout(pnlPlace12);
        pnlPlace12.setLayout(pnlPlace12Layout);
        pnlPlace12Layout.setHorizontalGroup(
            pnlPlace12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPos4)
                .addGap(18, 18, 18)
                .addComponent(lblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime4, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlace12Layout.setVerticalGroup(
            pnlPlace12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlace12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTime4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPlace12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPos4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPlace13.setBackground(new java.awt.Color(255, 255, 0));

        lblName5.setBackground(new java.awt.Color(255, 255, 255));
        lblName5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName5.setText("Ralph");

        lblTime5.setBackground(new java.awt.Color(255, 255, 255));
        lblTime5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTime5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime5.setText("5");

        lblPos5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPos5.setText("5");

        javax.swing.GroupLayout pnlPlace13Layout = new javax.swing.GroupLayout(pnlPlace13);
        pnlPlace13.setLayout(pnlPlace13Layout);
        pnlPlace13Layout.setHorizontalGroup(
            pnlPlace13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPos5)
                .addGap(18, 18, 18)
                .addComponent(lblName5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime5, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlace13Layout.setVerticalGroup(
            pnlPlace13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlace13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTime5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPlace13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPos5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPlace14.setBackground(new java.awt.Color(255, 255, 0));

        lblName6.setBackground(new java.awt.Color(255, 255, 255));
        lblName6.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName6.setText("Ralph");

        lblTime6.setBackground(new java.awt.Color(255, 255, 255));
        lblTime6.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTime6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime6.setText("5");

        lblPos6.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPos6.setText("6");

        javax.swing.GroupLayout pnlPlace14Layout = new javax.swing.GroupLayout(pnlPlace14);
        pnlPlace14.setLayout(pnlPlace14Layout);
        pnlPlace14Layout.setHorizontalGroup(
            pnlPlace14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPos6)
                .addGap(18, 18, 18)
                .addComponent(lblName6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime6, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlace14Layout.setVerticalGroup(
            pnlPlace14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlace14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTime6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPlace14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPos6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPlace15.setBackground(new java.awt.Color(255, 255, 0));

        lblName7.setBackground(new java.awt.Color(255, 255, 255));
        lblName7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblName7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName7.setText("Ralph");

        lblTime7.setBackground(new java.awt.Color(255, 255, 255));
        lblTime7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTime7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime7.setText("5");

        lblPos7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPos7.setText("7");

        javax.swing.GroupLayout pnlPlace15Layout = new javax.swing.GroupLayout(pnlPlace15);
        pnlPlace15.setLayout(pnlPlace15Layout);
        pnlPlace15Layout.setHorizontalGroup(
            pnlPlace15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPos7)
                .addGap(18, 18, 18)
                .addComponent(lblName7, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime7, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlace15Layout.setVerticalGroup(
            pnlPlace15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlace15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTime7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPlace15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPos7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPlace16.setBackground(new java.awt.Color(255, 255, 0));

        lblName8.setBackground(new java.awt.Color(255, 255, 255));
        lblName8.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblName8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName8.setText("Ralph");

        lblTime8.setBackground(new java.awt.Color(255, 255, 255));
        lblTime8.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTime8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime8.setText("5");

        lblPos8.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPos8.setText("8");

        javax.swing.GroupLayout pnlPlace16Layout = new javax.swing.GroupLayout(pnlPlace16);
        pnlPlace16.setLayout(pnlPlace16Layout);
        pnlPlace16Layout.setHorizontalGroup(
            pnlPlace16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPos8)
                .addGap(18, 18, 18)
                .addComponent(lblName8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime8, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlace16Layout.setVerticalGroup(
            pnlPlace16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlace16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlace16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTime8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPlace16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPos8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRecordDisplayLayout = new javax.swing.GroupLayout(pnlRecordDisplay);
        pnlRecordDisplay.setLayout(pnlRecordDisplayLayout);
        pnlRecordDisplayLayout.setHorizontalGroup(
            pnlRecordDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecordDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecordDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPlace1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlace10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlace11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlace12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlace13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlace14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlace15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlace16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlRecordDisplayLayout.setVerticalGroup(
            pnlRecordDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordDisplayLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlace10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlace11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlace12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlace13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlace14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlace15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlace16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pnlRecordDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(pnlSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlRecordDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // "Back" better clicked
        close(); // Close the screen
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbxOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxOperationActionPerformed
        
    }//GEN-LAST:event_cmbxOperationActionPerformed

    private void cmbxTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTargetActionPerformed
        
    }//GEN-LAST:event_cmbxTargetActionPerformed

    private void cmbxDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxDifficultyActionPerformed
        
    }//GEN-LAST:event_cmbxDifficultyActionPerformed

    private void btnGetRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRecordsActionPerformed
        // "Get Records" button clicked
        
        // Get the selected operation index
        this.CHOSEN_OPERATION_INDEX = cmbxOperation.getSelectedIndex();
        // Get the selected target index
        this.CHOSEN_TARGET_INDEX = cmbxTarget.getSelectedIndex();
        // Get the selected difficulty index
        this.CHOSEN_DIFFICULTY_INDEX = cmbxDifficulty.getSelectedIndex();
        
        // Get the enumerate for the chosen operation for the file handler
        this.CHOSEN_OPERATION = this.CHOSEN_OPERATION_INDEX;
        
        // Get the target score based on the TARGET_SCORE_INDEX
        switch (this.CHOSEN_TARGET_INDEX)
        {
            case 0:
                this.CHOSEN_TARGET = 10;
                break;
            case 1:
                this.CHOSEN_TARGET = 20;
                break;
            case 2:
                this.CHOSEN_TARGET = 30;
                break;
            case 3:
                this.CHOSEN_TARGET = 40;
                break;
            case 4:
                this.CHOSEN_TARGET = 50;
                break;
            case 5:
                this.CHOSEN_TARGET = 100;
                break;
            default:
                break;
        }
        
        // Set the chosen difficulty enumerate for the file handler
        this.CHOSEN_DIFFICULTY = this.CHOSEN_DIFFICULTY_INDEX + 1;
        
        // Get the new records
        updateRecords();
        
    }//GEN-LAST:event_btnGetRecordsActionPerformed

    private void updateRecords()
    {
        try {
            // Open the new file handler
            RecordsFileHandler rfh = new RecordsFileHandler(this.CHOSEN_DIFFICULTY, this.CHOSEN_OPERATION, this.CHOSEN_TARGET);
            
            // Set the times and names for each position
            lblName1.setText(rfh.getName(0));
            // getTime returns the number of milliseconds passed
            lblTime1.setText("" + ((double) (rfh.getTime(0) / 1000.0)));
            
            lblName2.setText(rfh.getName(1));
            lblTime2.setText("" + ((double) (rfh.getTime(1) / 1000.0)));
            
            lblName3.setText(rfh.getName(2));
            lblTime3.setText("" + ((double) (rfh.getTime(2) / 1000.0)));
            
            lblName4.setText(rfh.getName(3));
            lblTime4.setText("" + ((double) (rfh.getTime(3) / 1000.0)));
            
            lblName5.setText(rfh.getName(4));
            lblTime5.setText("" + ((double) (rfh.getTime(4) / 1000.0)));
            
            lblName6.setText(rfh.getName(5));
            lblTime6.setText("" + ((double) (rfh.getTime(5) / 1000.0)));
            
            lblName7.setText(rfh.getName(6));
            lblTime7.setText("" + ((double) (rfh.getTime(6) / 1000.0)));
            
            lblName8.setText(rfh.getName(7));
            lblTime8.setText("" + ((double) (rfh.getTime(7) / 1000.0)));
            
        } catch (IOException ex) {
            // An error happened :(
            Logger.getLogger(GUIRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void close()
    {
        // Make the previous GUI visible again
        this.parentGUI.setVisible(true);
        // Dispose this screen
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGetRecords;
    private javax.swing.JComboBox<String> cmbxDifficulty;
    private javax.swing.JComboBox<String> cmbxOperation;
    private javax.swing.JComboBox<String> cmbxTarget;
    private javax.swing.JLabel lblDifficulty;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName10;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblName9;
    private javax.swing.JLabel lblOperation;
    private javax.swing.JLabel lblPos1;
    private javax.swing.JLabel lblPos2;
    private javax.swing.JLabel lblPos3;
    private javax.swing.JLabel lblPos4;
    private javax.swing.JLabel lblPos5;
    private javax.swing.JLabel lblPos6;
    private javax.swing.JLabel lblPos7;
    private javax.swing.JLabel lblPos8;
    private javax.swing.JLabel lblTarget;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JLabel lblTime3;
    private javax.swing.JLabel lblTime4;
    private javax.swing.JLabel lblTime5;
    private javax.swing.JLabel lblTime6;
    private javax.swing.JLabel lblTime7;
    private javax.swing.JLabel lblTime8;
    private javax.swing.JLabel lblTime9;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlOperationSelect;
    private javax.swing.JPanel pnlOperationSelect1;
    private javax.swing.JPanel pnlOperationSelect2;
    private javax.swing.JPanel pnlPlace1;
    private javax.swing.JPanel pnlPlace10;
    private javax.swing.JPanel pnlPlace11;
    private javax.swing.JPanel pnlPlace12;
    private javax.swing.JPanel pnlPlace13;
    private javax.swing.JPanel pnlPlace14;
    private javax.swing.JPanel pnlPlace15;
    private javax.swing.JPanel pnlPlace16;
    private javax.swing.JPanel pnlPlace9;
    private javax.swing.JPanel pnlRecordDisplay;
    private javax.swing.JPanel pnlSelection;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables
}
